apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "airo.fullname" . }}
  labels:
    {{- include "airo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "airo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "airo.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "airo.serviceAccountName" . }}

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          args:
            - "--prometheus-url={{ .Values.prometheus.url }}"

          ports:
            - name: metrics
              containerPort: 8081
              protocol: TCP

          resources:
            {{- toYaml .Values.resources | nindent 12 }}